# -*- coding: utf-8 -*-
"""Real and fake news detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sFjfy65ULC_o2lcJ_i75J-t2SC08Bgv
"""

import pandas as pd
import numpy as np
import re

from google.colab import files

uploaded = files.upload()

true_df = pd.read_excel("synthetic_news_dataset_5000.xlsx")
fake_df = pd.read_excel("synthetic_fake_news_dataset_5000.xlsx")

true_df["label"] = 1
fake_df["label"] = 0

true_df["content"] = true_df["title"] + " " + true_df["text"]
fake_df["content"] = fake_df["title"] + " " + fake_df["text"]

df = pd.concat([true_df, fake_df], axis=0)
df = df.sample(frac=1).reset_index(drop=True)

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    return text

df["content"] = df["content"].apply(clean_text)

X = df["content"]
y = df["label"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=10000, stop_words="english")

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

def predict_news(news):
    news = news.lower()
    news = re.sub(r'[^a-zA-Z]', ' ', news)
    news = vectorizer.transform([news])
    pred = model.predict(news)

    if pred[0] == 1:
        print("Real News")
    else:
        print("Fake News")

predict_news(""" India won the 1983 world cup""")